# Declarative RabbitMQ configuration
# This configuration is not needed if default properties for RabbitMQ were used
spring:
  rabbitmq:
    port: 5672
    host: localhost
    username: guest
    password: guest
producer:
  queue-names:
    test-queue: testQueue   # Here you can set names for your queues